### ISSUE TITLE
.gitignore置く

### ISSUE THREAD

**Issue by shokai** [kentosasa/ProjectEuler#1]
macでemacs使ってる場合 `.gitignore` に

```
*~
*#*
.DS_Store
tmp/
*.log
```

とか書いておくと平和が訪れます

**Comment by kentosasa** [comment]
毎回gitignoreを作成するのがめんどくさそうだったので以下を参考にホームディレクトリに.gitignoreの設定を追加してみました。

http://qiita.com/asonas/items/abdbf1208e832b5dd0eb

**Comment by kentosasa** [comment]
レビューありがとうございます。

**Comment by shokai** [comment]
それだとホームディレクトリに設定してない人が変なプルリク作ってくるから俺はプロジェクト直下に置いてる

**Comment by kentosasa** [comment]
なるほど。
自分のパソコン以外のことも考えるとgitigonoreを作成したほうがいいのですね。
勉強になります。
